// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_identity_kyc`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2025-11-30, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `pezkuwi-dev`, CPU: `Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_identity_kyc`.
pub trait WeightInfo {
	fn apply_for_citizenship() -> Weight;
	fn approve_referral() -> Weight;
	fn confirm_citizenship() -> Weight;
	fn revoke_citizenship() -> Weight;
	fn renounce_citizenship() -> Weight;
	fn cancel_application() -> Weight;
	// Legacy aliases for backward compatibility
	fn apply_for_kyc() -> Weight { Self::apply_for_citizenship() }
	fn approve_kyc() -> Weight { Self::approve_referral() }
	fn revoke_kyc() -> Weight { Self::revoke_citizenship() }
}

/// Weights for `pallet_identity_kyc` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `IdentityKyc::KycStatuses` (r:2 w:1)
	/// Proof: `IdentityKyc::KycStatuses` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `IdentityKyc::Applications` (r:0 w:1)
	/// Proof: `IdentityKyc::Applications` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn apply_for_citizenship() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `6038`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(47_000_000, 6038)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	/// Storage: `IdentityKyc::KycStatuses` (r:1 w:1)
	/// Proof: `IdentityKyc::KycStatuses` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `IdentityKyc::Applications` (r:1 w:0)
	/// Proof: `IdentityKyc::Applications` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn approve_referral() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `180`
		//  Estimated: `3545`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(37_000_000, 3545)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	/// Storage: `IdentityKyc::KycStatuses` (r:1 w:1)
	/// Proof: `IdentityKyc::KycStatuses` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `IdentityKyc::Applications` (r:1 w:1)
	/// Proof: `IdentityKyc::Applications` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `IdentityKyc::IdentityHashes` (r:0 w:1)
	/// Proof: `IdentityKyc::IdentityHashes` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `IdentityKyc::CitizenReferrers` (r:0 w:1)
	/// Proof: `IdentityKyc::CitizenReferrers` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn confirm_citizenship() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `180`
		//  Estimated: `3545`
		// Minimum execution time: 55_000_000 picoseconds.
		Weight::from_parts(58_000_000, 3545)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}

	/// Storage: `IdentityKyc::KycStatuses` (r:1 w:1)
	/// Proof: `IdentityKyc::KycStatuses` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn revoke_citizenship() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `112`
		//  Estimated: `3514`
		// Minimum execution time: 26_900_000 picoseconds.
		Weight::from_parts(27_700_000, 3514)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	/// Storage: `IdentityKyc::KycStatuses` (r:1 w:1)
	/// Proof: `IdentityKyc::KycStatuses` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `IdentityKyc::IdentityHashes` (r:0 w:1)
	/// Proof: `IdentityKyc::IdentityHashes` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn renounce_citizenship() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `112`
		//  Estimated: `3514`
		// Minimum execution time: 30_000_000 picoseconds.
		Weight::from_parts(32_000_000, 3514)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	/// Storage: `IdentityKyc::KycStatuses` (r:1 w:1)
	/// Proof: `IdentityKyc::KycStatuses` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `IdentityKyc::Applications` (r:0 w:1)
	/// Proof: `IdentityKyc::Applications` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn cancel_application() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `112`
		//  Estimated: `3514`
		// Minimum execution time: 28_000_000 picoseconds.
		Weight::from_parts(30_000_000, 3514)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn apply_for_citizenship() -> Weight {
		Weight::from_parts(47_000_000, 6038)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	fn approve_referral() -> Weight {
		Weight::from_parts(37_000_000, 3545)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}

	fn confirm_citizenship() -> Weight {
		Weight::from_parts(58_000_000, 3545)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}

	fn revoke_citizenship() -> Weight {
		Weight::from_parts(27_700_000, 3514)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}

	fn renounce_citizenship() -> Weight {
		Weight::from_parts(32_000_000, 3514)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	fn cancel_application() -> Weight {
		Weight::from_parts(30_000_000, 3514)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
