
//! Autogenerated weights for `pallet_presale`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2025-11-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MamostePC`, CPU: `11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/pezkuwi
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_presale
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=pezkuwi/pallets/presale/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_presale`.
pub trait WeightInfo {
	fn create_presale() -> Weight;
	fn contribute() -> Weight;
	fn refund() -> Weight;
	fn cancel_presale() -> Weight;
	fn add_to_whitelist() -> Weight;
	fn claim_vested() -> Weight;
	fn refund_cancelled_presale() -> Weight;
	fn finalize_presale(n: u32) -> Weight;
	fn batch_refund_failed_presale(n: u32) -> Weight;
}

/// Weights for `pallet_presale` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Presale::NextPresaleId` (r:1 w:1)
	/// Proof: `Presale::NextPresaleId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Presale::Presales` (r:0 w:1)
	/// Proof: `Presale::Presales` (`max_values`: None, `max_size`: Some(252), added: 2727, mode: `MaxEncodedLen`)
	fn create_presale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `1489`
		// Minimum execution time: 11_457_000 picoseconds.
		Weight::from_parts(12_547_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Presale::Presales` (r:1 w:0)
	/// Proof: `Presale::Presales` (`max_values`: None, `max_size`: Some(252), added: 2727, mode: `MaxEncodedLen`)
	/// Storage: `Presale::Contributions` (r:1 w:1)
	/// Proof: `Presale::Contributions` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	/// Storage: `Presale::TotalRaised` (r:1 w:1)
	/// Proof: `Presale::TotalRaised` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:4 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Presale::Contributors` (r:1 w:1)
	/// Proof: `Presale::Contributors` (`max_values`: None, `max_size`: Some(320022), added: 322497, mode: `MaxEncodedLen`)
	/// Storage: `Presale::TotalPlatformVolume` (r:1 w:1)
	/// Proof: `Presale::TotalPlatformVolume` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Presale::TotalPlatformFees` (r:1 w:1)
	/// Proof: `Presale::TotalPlatformFees` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn contribute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1013`
		//  Estimated: `323487`
		// Minimum execution time: 165_062_000 picoseconds.
		Weight::from_parts(171_162_000, 0)
			.saturating_add(Weight::from_parts(0, 323487))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `Presale::Presales` (r:1 w:0)
	/// Proof: `Presale::Presales` (`max_values`: None, `max_size`: Some(252), added: 2727, mode: `MaxEncodedLen`)
	/// Storage: `Presale::Contributions` (r:1 w:1)
	/// Proof: `Presale::Contributions` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:4 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Presale::TotalRaised` (r:1 w:1)
	/// Proof: `Presale::TotalRaised` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn refund() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1622`
		//  Estimated: `11426`
		// Minimum execution time: 158_163_000 picoseconds.
		Weight::from_parts(162_619_000, 0)
			.saturating_add(Weight::from_parts(0, 11426))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `Presale::Presales` (r:1 w:1)
	/// Proof: `Presale::Presales` (`max_values`: None, `max_size`: Some(252), added: 2727, mode: `MaxEncodedLen`)
	fn cancel_presale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3717`
		// Minimum execution time: 14_097_000 picoseconds.
		Weight::from_parts(14_726_000, 0)
			.saturating_add(Weight::from_parts(0, 3717))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Presale::Presales` (r:1 w:0)
	/// Proof: `Presale::Presales` (`max_values`: None, `max_size`: Some(252), added: 2727, mode: `MaxEncodedLen`)
	/// Storage: `Presale::WhitelistedAccounts` (r:0 w:1)
	/// Proof: `Presale::WhitelistedAccounts` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn add_to_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3717`
		// Minimum execution time: 14_725_000 picoseconds.
		Weight::from_parts(15_523_000, 0)
			.saturating_add(Weight::from_parts(0, 3717))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Presale::Presales` (r:1 w:0)
	/// Storage: `Presale::Contributions` (r:1 w:0)
	/// Storage: `Presale::VestingClaimed` (r:1 w:1)
	/// Storage: `Presale::TotalRaised` (r:1 w:0)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Storage: `Assets::Account` (r:2 w:2)
	fn claim_vested() -> Weight {
		// Similar to contribute weight - involves asset transfer
		// Estimated based on storage operations
		Weight::from_parts(175_000_000, 0)
			.saturating_add(Weight::from_parts(0, 15000))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Presale::Presales` (r:1 w:0)
	/// Storage: `Presale::Contributors` (r:1 w:0)
	/// Storage: `Presale::Contributions` (r:N w:N)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Storage: `Assets::Account` (r:N w:N)
	/// O(N) complexity where N = number of contributors
	fn refund_cancelled_presale() -> Weight {
		// Base weight for cancelled presale refund
		// Uses same per-contributor estimate as finalize_presale
		let base = Weight::from_parts(25_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1));

		// Per-contributor refund weight (similar to regular refund)
		// Estimated ~160 µs per contributor
		let per_contributor = Weight::from_parts(160_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2));

		// Estimate for 10 contributors as default
		base.saturating_add(per_contributor.saturating_mul(10))
	}
	/// Storage: `Presale::Presales` (r:1 w:1)
	/// Storage: `Presale::Contributors` (r:1 w:0)
	/// Storage: `Presale::TotalRaised` (r:1 w:0)
	/// Storage: `Presale::Contributions` (r:N w:N)
	/// Storage: `Presale::VestingClaimed` (r:0 w:N) (if vesting enabled)
	/// Storage: `Presale::SuccessfulPresales` (r:1 w:1)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Storage: `Assets::Account` (r:N+1 w:N+1)
	/// O(N) complexity where N = number of contributors
	fn finalize_presale(n: u32) -> Weight {
		// Base weight: presale read + status update + analytics
		let base = Weight::from_parts(30_000_000, 0)
			.saturating_add(Weight::from_parts(0, 5000))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2));

		// Per-contributor weight: contribution read + reward transfer + vesting update
		// Measured ~180 µs per contributor based on contribute/refund weights
		let per_contributor = Weight::from_parts(180_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3000))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3));

		base.saturating_add(per_contributor.saturating_mul(n.into()))
	}
	/// Storage: `Presale::Presales` (r:1 w:0)
	/// Storage: `Presale::Contributors` (r:1 w:0)
	/// Storage: `Presale::Contributions` (r:N w:N)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Storage: `Assets::Account` (r:N+1 w:N+1)
	/// O(N) complexity where N = batch_size
	fn batch_refund_failed_presale(n: u32) -> Weight {
		// Base weight for batch refund
		let base = Weight::from_parts(25_000_000, 0)
			.saturating_add(Weight::from_parts(0, 5000))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1));

		// Per-contributor refund weight
		// Similar to regular refund but without fee distribution (failed presale = no fees)
		let per_contributor = Weight::from_parts(150_000_000, 0)
			.saturating_add(Weight::from_parts(0, 2500))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2));

		base.saturating_add(per_contributor.saturating_mul(n.into()))
	}
}
