// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_welati`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-11-30, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MamostePC`, CPU: `11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/mamostehp/Pezkuwi-SDK/target/release/pezkuwi-omni-node
// benchmark
// pallet
// --runtime=/home/mamostehp/Pezkuwi-SDK/target/release/wbuild/people-pezkuwichain-runtime/people_pezkuwichain_runtime.compact.compressed.wasm
// --pallet=pallet_welati
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=/home/mamostehp/Pezkuwi-SDK/cumulus/teyrchains/pallets/welati/src/weights.rs
// --template=/home/mamostehp/Pezkuwi-SDK/substrate/.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_welati`.
pub trait WeightInfo {
	fn initiate_election() -> Weight;
	fn register_candidate() -> Weight;
	fn cast_vote() -> Weight;
	fn finalize_election() -> Weight;
	fn nominate_official() -> Weight;
	fn approve_appointment() -> Weight;
	fn submit_proposal() -> Weight;
	fn vote_on_proposal() -> Weight;
}

/// Weights for `pallet_welati` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Welati::NextElectionId` (r:1 w:1)
	/// Proof: `Welati::NextElectionId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ActiveElections` (r:0 w:1)
	/// Proof: `Welati::ActiveElections` (`max_values`: None, `max_size`: Some(29354), added: 31829, mode: `MaxEncodedLen`)
	fn initiate_election() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `1489`
		// Minimum execution time: 11_156_000 picoseconds.
		Weight::from_parts(11_437_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Welati::ActiveElections` (r:1 w:1)
	/// Proof: `Welati::ActiveElections` (`max_values`: None, `max_size`: Some(29354), added: 31829, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ElectionCandidates` (r:1 w:1)
	/// Proof: `Welati::ElectionCandidates` (`max_values`: None, `max_size`: Some(3833), added: 6308, mode: `MaxEncodedLen`)
	fn register_candidate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `145`
		//  Estimated: `32819`
		// Minimum execution time: 20_471_000 picoseconds.
		Weight::from_parts(21_211_000, 32819)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Welati::ActiveElections` (r:1 w:1)
	/// Proof: `Welati::ActiveElections` (`max_values`: None, `max_size`: Some(29354), added: 31829, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ElectionVotes` (r:1 w:1)
	/// Proof: `Welati::ElectionVotes` (`max_values`: None, `max_size`: Some(435), added: 2910, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ElectionCandidates` (r:1 w:1)
	/// Proof: `Welati::ElectionCandidates` (`max_values`: None, `max_size`: Some(3833), added: 6308, mode: `MaxEncodedLen`)
	fn cast_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3532`
		//  Estimated: `32819`
		// Minimum execution time: 29_295_000 picoseconds.
		Weight::from_parts(30_319_000, 32819)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Welati::ActiveElections` (r:1 w:1)
	/// Proof: `Welati::ActiveElections` (`max_values`: None, `max_size`: Some(29354), added: 31829, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ElectionCandidates` (r:1 w:0)
	/// Proof: `Welati::ElectionCandidates` (`max_values`: None, `max_size`: Some(3833), added: 6308, mode: `MaxEncodedLen`)
	/// Storage: `IdentityKyc::KycStatuses` (r:2 w:0)
	/// Proof: `IdentityKyc::KycStatuses` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ElectionResults` (r:0 w:1)
	/// Proof: `Welati::ElectionResults` (`max_values`: None, `max_size`: Some(6467), added: 8942, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ParliamentMembers` (r:0 w:1)
	/// Proof: `Welati::ParliamentMembers` (`max_values`: Some(1), `max_size`: Some(11057), added: 11552, mode: `MaxEncodedLen`)
	fn finalize_election() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3684`
		//  Estimated: `32819`
		// Minimum execution time: 37_582_000 picoseconds.
		Weight::from_parts(39_409_000, 32819)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Welati::CurrentOfficials` (r:1 w:0)
	/// Proof: `Welati::CurrentOfficials` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::CurrentMinisters` (r:1 w:0)
	/// Proof: `Welati::CurrentMinisters` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::AppointedOfficials` (r:1 w:0)
	/// Proof: `Welati::AppointedOfficials` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::PendingNominations` (r:1 w:1)
	/// Proof: `Welati::PendingNominations` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `Welati::NextAppointmentId` (r:1 w:1)
	/// Proof: `Welati::NextAppointmentId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Welati::AppointmentProcesses` (r:0 w:1)
	/// Proof: `Welati::AppointmentProcesses` (`max_values`: None, `max_size`: Some(10119), added: 12594, mode: `MaxEncodedLen`)
	fn nominate_official() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `121`
		//  Estimated: `3638`
		// Minimum execution time: 26_499_000 picoseconds.
		Weight::from_parts(27_149_000, 3638)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Welati::CurrentOfficials` (r:1 w:0)
	/// Proof: `Welati::CurrentOfficials` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::AppointmentProcesses` (r:1 w:1)
	/// Proof: `Welati::AppointmentProcesses` (`max_values`: None, `max_size`: Some(10119), added: 12594, mode: `MaxEncodedLen`)
	/// Storage: `Welati::PendingNominations` (r:1 w:1)
	/// Proof: `Welati::PendingNominations` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `Welati::AppointedOfficials` (r:0 w:1)
	/// Proof: `Welati::AppointedOfficials` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn approve_appointment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `444`
		//  Estimated: `13584`
		// Minimum execution time: 30_310_000 picoseconds.
		Weight::from_parts(31_415_000, 13584)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Welati::ParliamentMembers` (r:1 w:0)
	/// Proof: `Welati::ParliamentMembers` (`max_values`: Some(1), `max_size`: Some(11057), added: 11552, mode: `MaxEncodedLen`)
	/// Storage: `Welati::CurrentOfficials` (r:1 w:0)
	/// Proof: `Welati::CurrentOfficials` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::NextProposalId` (r:1 w:1)
	/// Proof: `Welati::NextProposalId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ActiveProposals` (r:0 w:1)
	/// Proof: `Welati::ActiveProposals` (`max_values`: None, `max_size`: Some(1195), added: 3670, mode: `MaxEncodedLen`)
	fn submit_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119`
		//  Estimated: `12542`
		// Minimum execution time: 16_972_000 picoseconds.
		Weight::from_parts(17_828_000, 12542)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Welati::ActiveProposals` (r:1 w:1)
	/// Proof: `Welati::ActiveProposals` (`max_values`: None, `max_size`: Some(1195), added: 3670, mode: `MaxEncodedLen`)
	/// Storage: `Welati::CollectiveVotes` (r:1 w:1)
	/// Proof: `Welati::CollectiveVotes` (`max_values`: None, `max_size`: Some(612), added: 3087, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ParliamentMembers` (r:1 w:0)
	/// Proof: `Welati::ParliamentMembers` (`max_values`: Some(1), `max_size`: Some(11057), added: 11552, mode: `MaxEncodedLen`)
	fn vote_on_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `349`
		//  Estimated: `12542`
		// Minimum execution time: 21_839_000 picoseconds.
		Weight::from_parts(22_389_000, 12542)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Welati::NextElectionId` (r:1 w:1)
	/// Proof: `Welati::NextElectionId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ActiveElections` (r:0 w:1)
	/// Proof: `Welati::ActiveElections` (`max_values`: None, `max_size`: Some(29354), added: 31829, mode: `MaxEncodedLen`)
	fn initiate_election() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `1489`
		// Minimum execution time: 11_156_000 picoseconds.
		Weight::from_parts(11_437_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Welati::ActiveElections` (r:1 w:1)
	/// Proof: `Welati::ActiveElections` (`max_values`: None, `max_size`: Some(29354), added: 31829, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ElectionCandidates` (r:1 w:1)
	/// Proof: `Welati::ElectionCandidates` (`max_values`: None, `max_size`: Some(3833), added: 6308, mode: `MaxEncodedLen`)
	fn register_candidate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `145`
		//  Estimated: `32819`
		// Minimum execution time: 20_471_000 picoseconds.
		Weight::from_parts(21_211_000, 32819)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Welati::ActiveElections` (r:1 w:1)
	/// Proof: `Welati::ActiveElections` (`max_values`: None, `max_size`: Some(29354), added: 31829, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ElectionVotes` (r:1 w:1)
	/// Proof: `Welati::ElectionVotes` (`max_values`: None, `max_size`: Some(435), added: 2910, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ElectionCandidates` (r:1 w:1)
	/// Proof: `Welati::ElectionCandidates` (`max_values`: None, `max_size`: Some(3833), added: 6308, mode: `MaxEncodedLen`)
	fn cast_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3532`
		//  Estimated: `32819`
		// Minimum execution time: 29_295_000 picoseconds.
		Weight::from_parts(30_319_000, 32819)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Welati::ActiveElections` (r:1 w:1)
	/// Proof: `Welati::ActiveElections` (`max_values`: None, `max_size`: Some(29354), added: 31829, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ElectionCandidates` (r:1 w:0)
	/// Proof: `Welati::ElectionCandidates` (`max_values`: None, `max_size`: Some(3833), added: 6308, mode: `MaxEncodedLen`)
	/// Storage: `IdentityKyc::KycStatuses` (r:2 w:0)
	/// Proof: `IdentityKyc::KycStatuses` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ElectionResults` (r:0 w:1)
	/// Proof: `Welati::ElectionResults` (`max_values`: None, `max_size`: Some(6467), added: 8942, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ParliamentMembers` (r:0 w:1)
	/// Proof: `Welati::ParliamentMembers` (`max_values`: Some(1), `max_size`: Some(11057), added: 11552, mode: `MaxEncodedLen`)
	fn finalize_election() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3684`
		//  Estimated: `32819`
		// Minimum execution time: 37_582_000 picoseconds.
		Weight::from_parts(39_409_000, 32819)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Welati::CurrentOfficials` (r:1 w:0)
	/// Proof: `Welati::CurrentOfficials` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::CurrentMinisters` (r:1 w:0)
	/// Proof: `Welati::CurrentMinisters` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::AppointedOfficials` (r:1 w:0)
	/// Proof: `Welati::AppointedOfficials` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::PendingNominations` (r:1 w:1)
	/// Proof: `Welati::PendingNominations` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `Welati::NextAppointmentId` (r:1 w:1)
	/// Proof: `Welati::NextAppointmentId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Welati::AppointmentProcesses` (r:0 w:1)
	/// Proof: `Welati::AppointmentProcesses` (`max_values`: None, `max_size`: Some(10119), added: 12594, mode: `MaxEncodedLen`)
	fn nominate_official() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `121`
		//  Estimated: `3638`
		// Minimum execution time: 26_499_000 picoseconds.
		Weight::from_parts(27_149_000, 3638)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Welati::CurrentOfficials` (r:1 w:0)
	/// Proof: `Welati::CurrentOfficials` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::AppointmentProcesses` (r:1 w:1)
	/// Proof: `Welati::AppointmentProcesses` (`max_values`: None, `max_size`: Some(10119), added: 12594, mode: `MaxEncodedLen`)
	/// Storage: `Welati::PendingNominations` (r:1 w:1)
	/// Proof: `Welati::PendingNominations` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `Welati::AppointedOfficials` (r:0 w:1)
	/// Proof: `Welati::AppointedOfficials` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn approve_appointment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `444`
		//  Estimated: `13584`
		// Minimum execution time: 30_310_000 picoseconds.
		Weight::from_parts(31_415_000, 13584)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Welati::ParliamentMembers` (r:1 w:0)
	/// Proof: `Welati::ParliamentMembers` (`max_values`: Some(1), `max_size`: Some(11057), added: 11552, mode: `MaxEncodedLen`)
	/// Storage: `Welati::CurrentOfficials` (r:1 w:0)
	/// Proof: `Welati::CurrentOfficials` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::NextProposalId` (r:1 w:1)
	/// Proof: `Welati::NextProposalId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ActiveProposals` (r:0 w:1)
	/// Proof: `Welati::ActiveProposals` (`max_values`: None, `max_size`: Some(1195), added: 3670, mode: `MaxEncodedLen`)
	fn submit_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119`
		//  Estimated: `12542`
		// Minimum execution time: 16_972_000 picoseconds.
		Weight::from_parts(17_828_000, 12542)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Welati::ActiveProposals` (r:1 w:1)
	/// Proof: `Welati::ActiveProposals` (`max_values`: None, `max_size`: Some(1195), added: 3670, mode: `MaxEncodedLen`)
	/// Storage: `Welati::CollectiveVotes` (r:1 w:1)
	/// Proof: `Welati::CollectiveVotes` (`max_values`: None, `max_size`: Some(612), added: 3087, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ParliamentMembers` (r:1 w:0)
	/// Proof: `Welati::ParliamentMembers` (`max_values`: Some(1), `max_size`: Some(11057), added: 11552, mode: `MaxEncodedLen`)
	fn vote_on_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `349`
		//  Estimated: `12542`
		// Minimum execution time: 21_839_000 picoseconds.
		Weight::from_parts(22_389_000, 12542)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
